const report = {
  cutoff: '2026-09-12 deployed Chrome Support Operations campaign',
  sizes: ['360×800','390×844','768×1024','1024×768','1280×800','1440×900'],
  scenarios: [
    ['SUP-001','FAIL','Admin messaging and conversation access','Two-way messaging and persistence work, but the operational close/escalate/reopen, attachment, privacy and failure-recovery contract is incomplete.'],
    ['SUP-002','FAIL','Notification operations, templates, delivery and replay','In-app delivery works; controlled email delivery failed and template preview accepts malformed sample JSON.'],
    ['SUP-003','FAIL','Feedback operations full lifecycle','Create, respond, status, reopen and audit paths work; launcher reachability and SLA date rendering remain incorrect.'],
    ['SUP-004','BLOCKED','Support queue, chat, call and recording','Queue/filter/history render, but a fresh transferable case and independent consented media endpoint were unavailable for the full lifecycle.'],
    ['SUP-005','FAIL','Moderation, support and feedback cross-case linkage','The visible linkage action only accepts a GitHub issue or PR; support and moderation cases cannot be linked.']
  ],
  findings: [
    {id:'SUP-F001',severity:'High',scenario:'SUP-001',area:'Messaging lifecycle',title:'Operational conversations lack a complete case lifecycle',steps:'Open Admin Messaging, inspect a controlled operational thread, and look for close, escalation, reopen and case-linked attachment controls.',description:'Direct two-way messaging persists, but the required operational lifecycle and associated recovery/privacy branches cannot be completed from the visible workflow.',expected:'Authorized support staff should be able to progress one auditable operational thread through attachment, escalation, closure and reopen without leaving the case context.',evidenceStatus:'Observed product gap'},
    {id:'SUP-F002',severity:'High',scenario:'SUP-002',area:'Email delivery',title:'Direct test email is not delivered to the controlled inbox',steps:'Send one test notification with in-app and email channels, then reconcile the event log, recipient notification center and controlled Gmail inbox.',description:'The in-app notification arrived, while the email channel recorded provider failure/fallback activity and no matching message reached the controlled inbox after the bounded follow-up window.',expected:'A reported email send must produce one traceable inbox delivery or a terminal actionable failure with provider correlation.',evidenceStatus:'Observed defect'},
    {id:'SUP-F003',severity:'Medium',scenario:'SUP-002',area:'Template validation',title:'Malformed template sample JSON silently previews default data',steps:'Open Template management, enter malformed sample JSON, and select Preview.',description:'Preview reports success and silently substitutes the default sample instead of rejecting the malformed input.',expected:'Malformed JSON should be rejected with a precise, recoverable validation message and must not masquerade as the supplied sample.',evidenceStatus:'Observed defect'},
    {id:'SUP-F004',severity:'Medium',scenario:'SUP-002',area:'Template rendering',title:'Benign markup displays literal entity text in preview',steps:'Preview a benign Unicode sample containing markup-like text in the declared template variable.',description:'The subject, in-app body and rendered HTML preview expose literal encoded entity strings, making the operator preview differ from expected readable output.',expected:'Preview should safely escape unsafe markup while presenting the intended human-readable text consistently across channels.',evidenceStatus:'Observed UX defect'},
    {id:'SUP-F005',severity:'Medium',scenario:'SUP-003',area:'Feedback entry',title:'Feedback launcher is absent on Admin portal pages despite enabled visibility',steps:'Enable the feedback launcher, refresh an Admin portal page at the supported Chrome widths, and inspect visible and accessible controls.',description:'The setting remains enabled, but the launcher is absent on Admin portal pages; it is only available on selected messaging or feedback surfaces.',expected:'The every-page launcher promise should be honored consistently, or the setting and copy should clearly describe its limited scope.',evidenceStatus:'Observed defect'},
    {id:'SUP-F006',severity:'Medium',scenario:'SUP-003',area:'SLA dates',title:'Feedback SLA date shifts to the prior local day',steps:'Assign a controlled feedback case, choose a date-only SLA, save, reopen, and compare the Admin, submitter and audit displays.',description:'A selected September 12 SLA persists as midnight UTC and renders as September 11 at 5:00 PM in Phoenix.',expected:'A date-only SLA must remain the selected calendar date across timezones and all role views.',evidenceStatus:'Observed defect'},
    {id:'SUP-F007',severity:'Medium',scenario:'SUP-004',area:'Queue metrics',title:'Support actionable count includes terminal records',steps:'Compare the Support Operations command-center count with the All queue grouped by terminal and actionable states.',description:'The count is eight even though six records are Cancelled or Completed and only two are Calling or In queue.',expected:'Actionable queue metrics should exclude terminal work or label the value clearly as total historical requests.',evidenceStatus:'Observed UX defect'},
    {id:'SUP-F008',severity:'High',scenario:'SUP-005',area:'Cross-case coordination',title:'Support, moderation and feedback cases cannot be linked',steps:'Open an existing feedback case, select Link issue, and inspect the allowed relationship target; then inspect the corresponding Support Queue record.',description:'The only visible linkage dialog accepts a GitHub issue or pull request. No relationship control or shared case model links feedback to support or moderation records.',expected:'Related operational cases should share immutable, role-limited cross-references so staff can coordinate action and closure without copying private evidence.',evidenceStatus:'Observed product gap'}
  ],
  gaps: [
    ['Fresh support lifecycle','SUP-004','A disposable queued case, competing agent and independent media endpoint were not available for transfer, reconnect and consented call/recording proof.'],
    ['Independent realtime context','SUP-001','The completed messaging evidence used sequential role sessions rather than two simultaneously authenticated independent contexts.'],
    ['Cross-case capability','SUP-005','The deployed product exposes GitHub linkage only, blocking the authored support/moderation/feedback lifecycle by design.']
  ]
};

const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.PR_REVIEW_DATA={meta:{commit:'8780f40d',generatedAt:'2026-09-12T07:02:00Z',checkpoint:report.cutoff,url:'https://github.com/capitalinvestmentclub/support-operations-uat-report'},findings:report.findings.map(f=>({...f,type:f.severity==='Medium'?'Gap':'Defect',status:'Open',source:`tests/e2e/admin/${f.scenario}`,line:1,sourceUrl:'https://github.com/capitalinvestmentclub/support-operations-uat-report',evidenceUrl:'',visuals:[]}))};
document.getElementById('scenarios').innerHTML=report.scenarios.map(([id,status,title,observation])=>`<tr id="scenario-${id.toLowerCase()}"><td>${escapeText(id)}<br>${escapeText(title)}<br><span class="history">${escapeText(status)}</span></td><td>${escapeText(status)} · ${escapeText(observation)}</td><td>${status==='BLOCKED'?'Supply the documented controlled fixtures, then rerun.':'Fix the linked findings and rerun this exact scenario.'}</td><td><div class="cells">${report.sizes.map(size=>`<span>${size} · ${escapeText(status)}</span>`).join('')}</div></td></tr>`).join('');
document.getElementById('gaps').innerHTML=report.gaps.map(([title,scope,body])=>`<article><h3>${escapeText(title)}</h3><small>${escapeText(scope)}</small><p>${escapeText(body)}</p></article>`).join('');
